import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from './components/provider';
import Login from './components/login';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <h1>Heading 1</h1>
          <Login />
          {children}
        </body>
      </Providers>
    </html>
  );
}
